# Generated by Django 5.1.1 on 2024-09-04 12:37

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pools', to='Games.region')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('played', models.IntegerField(null=True)),
                ('won', models.IntegerField(null=True)),
                ('loss', models.IntegerField(null=True)),
                ('draw', models.IntegerField(null=True)),
                ('f', models.IntegerField(null=True)),
                ('agg', models.IntegerField(null=True)),
                ('plusminus', models.IntegerField(null=True)),
                ('points', models.IntegerField(null=True)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='Games.pool')),
            ],
        ),
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('upcoming', 'upcoming'), ('live', 'live'), ('played', 'played'), ('postponed', 'postponed')], max_length=100, null=True)),
                ('homeresults', models.IntegerField(null=True)),
                ('awayresults', models.IntegerField(null=True)),
                ('time', models.TimeField(default=datetime.time(15, 30))),
                ('away', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away', to='Games.team')),
                ('home', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home', to='Games.team')),
            ],
        ),
    ]
