# Generated by Django 5.1.1 on 2024-09-06 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
